# Ball-Prune small config (O(N^2) build; keep N small)
outdir: results
metric: l2
warmup: 5
data_dir: data

algorithms:
  - name: ball_prune

# Small dataset to keep build time reasonable
# Format: toy_{dist}_N{N}_D{D}_nq{nq}_seed{seed}
datasets:
  - toy_gaussian_N100_D2_nq10_seed42

k_values: [1, 10]

