# Minimal KNN bench config
outdir: results
metric: l2
warmup: 10
data_dir: data

algorithms:
  - name: bruteforce_numpy

# small, fast-to-run dataset key
# will be generated on the fly if missing
# format: toy_{dist}_N{N}_D{D}_nq{nq}_seed{seed}
datasets:
  - toy_gaussian_N10000_D64_nq200_seed42

k_values: [1, 10]

